name: Run Tests and Publish Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests and Generate Allure Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install Dependencies
        run: npm ci

      - name: Set up Android SDK and Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -o cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --verbose
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --verbose "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;arm64-v8a" "emulator"

          echo "Procurando o adb instalado..."
          find $ANDROID_HOME -name adb -type f || { echo "Erro: adb não foi encontrado. Verifique a instalação do platform-tools."; exit 1; }

          export PATH=$ANDROID_HOME/platform-tools:$PATH
          echo "Verificando adb..."
          $ANDROID_HOME/platform-tools/adb version || { echo "Erro: ADB não está acessível. Verifique a instalação do platform-tools."; exit 1; }

          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;arm64-v8a" --device "pixel_3" --force

          echo "Exportando variáveis para o ambiente global..."
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Install Missing Libraries for Emulator
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libpulse0

      - name: Start Metro Bundler
        run: |
          nohup npm start -- --reset-cache &> metro.log &
          echo "Esperando o Metro Bundler inicializar..."
          sleep 15

      - name: Build Android Release
        run: npm run android.release.ci

      - name: Start Appium Server
        run: |
          nohup appium --port 4723 &> appium.log &
          echo "Esperando o Appium Server inicializar..."
          sleep 15

      - name: Run Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-accel &> emulator.log &
          echo "Esperando o emulador inicializar..."
          adb wait-for-device
          for i in {1..2}; do
            if adb shell getprop sys.boot_completed | grep -m 1 '1'; then
              echo "Emulador inicializado com sucesso!"
              break
            fi
            echo "Esperando o emulador inicializar... Tentativa $i"
            sleep 20
          done
          adb devices || { echo "Erro: Nenhum dispositivo detectado pelo adb."; exit 1; }
        continue-on-error: true

      - name: Check Emulator Logs
        if: failure()
        run: cat emulator.log

      - name: Install Allure CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-11-jdk
          wget -qO- https://github.com/allure-framework/allure2/releases/download/2.22.3/allure-2.22.3.tgz | tar -xz -C /opt/
          echo 'export PATH=$PATH:/opt/allure-2.22.3/bin' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Run Tests
        run: npm run test.ci

      - name: Generate Allure Report
        run: |
          if [ -d "allure-results" ]; then
            allure generate allure-results --clean
          else
            echo "Diretório allure-results não encontrado. Certifique-se de que os resultados dos testes foram salvos."
            exit 1
          fi

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    name: Deploy Allure Report to GitHub Pages
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
