name: Run Tests and Publish Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests and Generate Allure Report
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Instala dependências
      - name: Install Dependencies
        run: npm ci

      # Configuração do Android SDK e Emulador
      - name: Set up Android SDK and Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_AVD_HOME=$HOME/.android/avd
          export ANDROID_SDK_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          # Criar diretório para o SDK
          mkdir -p $ANDROID_HOME/cmdline-tools

          # Baixar e descompactar o Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -o cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools

          # Ajustar estrutura do Command Line Tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          # Atualizar SDK Manager e listar pacotes disponíveis
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list

          # Aceitar licenças e instalar pacotes necessários
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "system-images;android-31;google_apis;arm64-v8a" "emulator"

          # Criar e configurar o AVD
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-31;google_apis;arm64-v8a" --force --device "pixel_3"

          # Verificar se o AVD foi criado
          if [ ! -f "$HOME/.android/avd/test.ini" ]; then
            echo "Erro: AVD 'test' não foi criado."
            exit 1
          fi

          # Inicie o emulador
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-load -no-window -gpu swiftshader_indirect -memory 2048 &

          # Aguardar inicialização do emulador
          adb wait-for-device
          adb shell input keyevent 82

      # Instalação do Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-11-jdk
          wget -qO- https://github.com/allure-framework/allure2/releases/download/2.22.3/allure-2.22.3.tgz | tar -xz -C /opt/
          echo 'export PATH=$PATH:/opt/allure-2.22.3/bin' >> $GITHUB_ENV

      # Executa os testes e gera os resultados do Allure
      - name: Run Tests
        run: npx wdio run wdio.conf.js --spec tests/specs/test.spec.js

      # Gera o relatório Allure
      - name: Generate Allure Report
        run: |
          if [ -d "allure-results" ]; then
            allure generate allure-results --clean
          else
            echo "Diretório allure-results não encontrado. Certifique-se de que os resultados dos testes foram salvos."
            exit 1
          fi

      # Faz upload do relatório gerado para a workspace
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    name: Deploy Allure Report to GitHub Pages
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Faz download do relatório gerado
      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report

      # Publica o relatório no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
